### ISSUE TITLE
[Bug Report] Subscription Manager always shows "No subscriptions found." even with subscriptions added

### ISSUE THREAD

**Issue by melyux** [getmango/Mango#329]
**Describe the bug**
The Subscription Manager always shows "No subscriptions found." despite subscriptions existing and working.

**To Reproduce**
1. Go to Download > Plugins, create a subscription, confirm that the `subscriptions.json` file exists under the plugin.
2. Optionally, wait until a new chapter comes out and see that it downloads automatically.
3. Go to Download > Subscription Manager.
4. See "No subscriptions found.":
<img width="948" alt="image" src="https://user-images.githubusercontent.com/10296053/184708206-13103557-d999-4da0-adbf-afd1a2409a5c.png">

**Expected behavior**
I assume there's normally a table to view and edit existing subscriptions.

**Environment (please complete the following information):**
 - OS: Docker
 - Browser: Safari, Chrome
 - Mango Version: Latest (0.27.0)

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.
```yml
  mango:
    image: hkalexling/mango
    container_name: mango
    expose:
      - 9000
    ports:
      - 9000:9000
    volumes:
      - ./mango/data:/root/mango
      - ./mango/config:/root/.config/mango
```

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.
(See screenshot above)
