### ISSUE TITLE
[Bug Report] mango.db is not persistent in the Docker Image

### ISSUE THREAD

**Issue by LostOnTheLine** [getmango/Mango#341]
**Describe the bug**
The Mango.db file defaults to a location that is not saved in the Docker-Compose provided with the Docker Image. It is saved in `/root` while it mounts `/root/mango`. If one does not change the location in the config file the database is lost on a restart. & then you have to delete the cache, & start from scratch, getting a new admin password & creating new users

**To Reproduce**
Run the docker as it's specified on DockerHub
Create a user
Add a manga
Stop the container/stack
Start the container/stack

**Expected behavior**
Your users are supposed to be kept between sessions

**Environment (please complete the following information):**
 - OS: Docker Desktop on Windows
 - Browser N/A
 - Mango Version: v0.27.0

**Docker (if you are running Mango in a Docker container)**
- The `docker-compose.yml` file you are using, or your `.env` file.
```
version: '3'
services:
  mango:
    image: hkalexling/mango
    container_name: mango
    ports:
      - 9001:9000
    environment:
      - TZ=America/Phoenix    #Though this doesn't seem to work as the logs are still in GMT
    volumes:
      - /k/mango/mango:/root/mango
      - /k/mango/config:/root/.config/mango
      - /k/mango/mango.db:/root/mango.db    # This was added to fix the problem. optionally you could mount the whole "/Root" directory but it's already not ideal that the library & upload directories are within the mango directory where the queue.db & other persistent files live
```

**Additional context**
Add any other context about the problem here. Add screenshots if applicable.
